# Generated by Django 4.2.3 on 2023-07-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_gallery_property_property_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='single_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.singleimage'),
        ),
    ]
